### PR TITLE
Sample copy editing

### PR DESCRIPTION
**Pull request by justbennet**
Michael, I am a computer support person and I using your guide to learn about fMRI analysis so I can show people how to run the software on our compute cluster.  I was at one time a copy editor for the American Statistical Association.  I made some sample editorial changes to the beginning of this section and am submitting a pull request to see whether you approve of them and would like me to submit more, as I can get to them.

Thanks for the tremendous work put into this.

-- bennet
University of Michigan, Ann Arbor

### CODE REVIEW

**Comment by miykael** [comment]
Hi bennet. That would be great! :-) I'm not a native English speaker and sometimes seem to write too much phonetically or with the German grammar in mind.
You're corrections are already very good (and very much needed). So, please feel free to correct as much as you want. I would be very grateful!!!
Michael

PS: If you think some parts are missing or are not understandable. Please let me know!

**Comment by justbennet** [comment]
Michael,

I will proceed then.  I'll try to keep pull requests to one page or less to make it easier for you to review a set of changes before you decide to accept them.

Your written English is excellent with the occasional slip.  I wish my student workers could write so well!

Thanks,  -- bennet

**Comment by justbennet** [comment]
Michael,

In nipype.rst, you have

* **Node**: A node wraps an interface so that it can be used in a workflow (or as a standalone).

I was thinking that might be kind of computerese to some people who might be just starting.  Do you think this version is accurate and better?

* **Node**: A node provides the information -- parameters, filenames, etc. -- that is needed by an interface to run the program properly for a particular job, whether as part of a workflow or separately.

That's kind of a bigger change than most, so I thought it worth asking first.

**Comment by miykael** [comment]
Bennet,
This is amazing! I like this suggestion very much. It sounds much more like an actual guide and not anymore like an IT-user lexicon. I'm very happy if you make such bigger changes.
Thanks, Michael

**Pull request merged**
